CREATE TABLE product(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    price DECIMAL(10,2) NOT NULL CHECK(price > 0),
    stock INT NOT NULL CHECK(stock >= 0),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);